CREATE TABLE IF NOT EXISTS daybook (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	day INTEGER NOT NULL,
	month INTEGER NOT NULL,
	zagolovok TEXT NOT NULL DEFAULT '',
	zadacha TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL DEFAULT ''
)