CREATE TABLE IF NOT EXISTS daybook (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	zagolovok TEXT NOT NULL,
	zadacha TEXT NOT NULL DEFAULT ' ',
	status TEXT NOT NULL DEFAULT 'Не закончена',
	created DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
)
